spring:
  application.name: doping-technology-case

  ####
  # h2 db
  #h2:
    #console.enabled: true

  # datasource
  #datasource.url: jdbc:h2:mem:test


  datasource:
    url: jdbc:postgresql://localhost:5432/doping-case?user=postgres&password=postgres


  # jpa
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect